lr: 0.001 # learning rate
epochs: 200
noise_dim: 0 # noise vector to concatenate with input prompt features to add diversity
dim: 128 # dim of th hidden state
depth: 8 # nb of layers
dropout: 0
cutn: 8 # number of random data augmentations per generate image
batch_size: 8
repeat: 1 # number of generated images per prompt
nb_noise: null # number of unique noise vectors
diversity_coef: 0 # diversity loss coeficient
vqgan_config: "vqgan_imagenet_f16_16384.yaml"
vqgan_checkpoint: "vqgan_imagenet_f16_16384.ckpt"
clip_model: "ViT-B/32"
path: data/MIT_states_train.txt # data path
folder: results/example # results path
log_interval: 100
