lr: 0.001
epochs: 200
noise_dim: 0
dim: 128
depth: 8
dropout: 0
cutn: 8
batch_size: 8
repeat: 1
nb_noise: null
diversity_coef: 0
vqgan_config: "vqgan_imagenet_f16_16384.yaml"
vqgan_checkpoint: "vqgan_imagenet_f16_16384.ckpt"
clip_model: "ViT-B/32"
path: data/MIT_states_train.txt
